#!/usr/bin/env python3
"""
build_src_rec_with_tele.py

Merge the regional (JMA/Hi-net, Jan-2020) src_rec file with the ISC-based
teleseismic source set into one TomoATT src_rec file for joint regional +
teleseismic inversion.

  - local events (inside the box, abs_time data): kept unchanged from
    src_rec_file_japan_filtered.dat
  - teleseismic events (outside the box, cs_dif_time data): appended as
    additional source blocks with receivers = Japanese stations and
    travel_time = ISC arrival time - ISC prime origin time.

TomoATT treats any source located outside the study region as teleseismic
when `have_tele_data: true` is set in the input params; the common-source
differential time inversion (use_cs_time: true) is then applied to those
blocks so that origin-time / outside-region path errors cancel.

Inputs:
  src_rec_file_japan_2020_filtered.dat      (year-2020 JMA QCed dataset)
  ../1_data_acquisition/isc_teleseismic/isc_tele_p_arrivals_2020.csv

Output:
  src_rec_file_japan_2020_tele.dat          (merged v3 catalog)
  tele_station_summary_2020.csv             (tele receiver inventory)
"""

import csv
from datetime import datetime
from pathlib import Path
from collections import defaultdict

SCRIPT_DIR = Path(__file__).parent.resolve()
LOCAL_SRC_REC = SCRIPT_DIR / "src_rec_file_japan_2020_filtered.dat"
TELE_CSV = (SCRIPT_DIR / ".." / "1_data_acquisition" /
            "isc_teleseismic" / "isc_tele_p_arrivals_2020.csv")
OUT_FILE = SCRIPT_DIR / "src_rec_file_japan_2020_tele.dat"
OUT_STA = SCRIPT_DIR / "tele_station_summary_2020.csv"

DEFAULT_MAG = 5.5   # ISC rows with empty magnitude column get this nominal value


def parse_dt(date_str, time_str):
    s = f"{date_str} {time_str}"
    return datetime.strptime(s, "%Y-%m-%d %H:%M:%S.%f") if "." in s \
        else datetime.strptime(s, "%Y-%m-%d %H:%M:%S")


def build_tele_abs_file(events, path):
    """Write a tele-only src_rec file with correct TomoATT column order:
    receiver lines are `<src_id> <rec_id> name lat lon elev phase tt weight`.
    (column 0 = source id, column 1 = receiver id — required by
    pytomoatt SrcRec / consistent with the regional file.)"""
    with open(path, "w") as out:
        for i, (ev_id, picks) in enumerate(sorted(events.items())):
            p0 = picks[0]
            to = parse_dt(*p0["origin_time_utc"].split("T"))
            sec = to.second + to.microsecond / 1e6
            evla = float(p0["evla"]); evlo = float(p0["evlo"])
            evdep = float(p0["evdep_km"])
            mag = float(p0["mag"]) if p0["mag"] else DEFAULT_MAG
            out.write(
                f"{i}  {to.year}  {to.month}  {to.day}  {to.hour}  "
                f"{to.minute}  {sec:9.3f}  "
                f"{evla:12.6f}  {evlo:12.6f}  {evdep:9.3f}  "
                f"{mag:6.2f}  {len(picks)}  tel_{ev_id}  1.000\n"
            )
            for j, p in enumerate(picks):
                out.write(
                    f"{i}  {j}  {p['sta']}  {float(p['stla']):12.6f}  "
                    f"{float(p['stlo']):12.6f}  {0.0:8.2f}  P  "
                    f"{float(p['travel_time_s']):12.4f}  1.000\n"
                )
    return path


def build_tele_cs_blocks(events, max_azi_gap=30.0, max_dist_gap=5.0):
    """Return (headers, pair_lines, station_set) with common-source
    differential pairs generated by PyTomoATT (type='cs')."""
    from pytomoatt.src_rec import SrcRec
    import tempfile
    tmp = Path(tempfile.gettempdir()) / "tele_abs_for_cs.dat"
    build_tele_abs_file(events, tmp)
    sr = SrcRec.read(str(tmp))
    sr.generate_double_difference(type="cs", max_azi_gap=max_azi_gap,
                                  max_dist_gap=max_dist_gap)
    cs = sr.rec_points_cs
    print(f"pytomoatt cs pairs   : {len(cs)}")

    # group pair rows per tele event (source index = position in sorted events)
    ev_keys = sorted(events.keys())
    headers, blocks = {}, {}
    station_set = set()
    for sidx, ev_id in enumerate(ev_keys):
        sub = cs[cs.src_index == sidx]
        blocks[ev_id] = sub
        for _, row in sub.iterrows():
            station_set.add((row.staname1, row.stla1, row.stlo1))
            station_set.add((row.staname2, row.stla2, row.stlo2))
    return headers, blocks, station_set


def main():
    # ---------------- load tele arrivals ----------------------------------
    events = defaultdict(list)   # ev_id -> list of pick dicts
    with open(TELE_CSV) as f:
        for r in csv.DictReader(f):
            events[r["ev_id"]].append(r)

    # ---------------- cs pairs for tele events ----------------------------
    _, blocks, station_set = build_tele_cs_blocks(
        events, max_azi_gap=30.0, max_dist_gap=5.0)

    # ---------------- write merged file -----------------------------------
    with open(LOCAL_SRC_REC) as fin, open(OUT_FILE, "w") as fout:
        local_text = fin.read()
        fout.write(local_text.rstrip() + "\n")

        # count local event blocks (event lines have 14 columns; receiver
        # lines have 9) so tele source ids do not collide with local ones
        id_offset = sum(1 for ln in local_text.splitlines()
                        if len(ln.split()) == 14)
        print(f"local event blocks   : {id_offset}")

        n_events = 0
        pair_count = 0
        for k, (ev_id, picks) in enumerate(sorted(events.items())):
            sub = blocks[ev_id]
            if len(sub) == 0:
                continue        # event without any cs pair -> dropped
            i = id_offset + k
            ev_p0 = picks[0]
            evla = float(ev_p0["evla"])
            evlo = float(ev_p0["evlo"])
            evdep = float(ev_p0["evdep_km"])
            mag = float(ev_p0["mag"]) if ev_p0["mag"] else DEFAULT_MAG
            to = parse_dt(*ev_p0["origin_time_utc"].split("T"))
            sec = to.second + to.microsecond / 1e6

            fout.write(
                f"{i}  {to.year}  {to.month}  {to.day}  {to.hour}  "
                f"{to.minute}  {sec:9.3f}  "
                f"{evla:12.6f}  {evlo:12.6f}  {evdep:9.3f}  "
                f"{mag:6.2f}  {len(sub)}  tel_{ev_id}  1.000\n"
            )
            for j, (_, row) in enumerate(sub.iterrows()):
                fout.write(
                    f"{i}  {j}  {row.staname1}  {row.stla1:12.6f}  "
                    f"{row.stlo1:12.6f}  {row.stel1:8.2f}  "
                    f"{int(row.rec_index2)}  {row.staname2}  {row.stla2:12.6f}  "
                    f"{row.stlo2:12.6f}  {row.stel2:8.2f}  "
                    f"{row.phase}  {row.tt:12.4f}  {row.weight:6.3f}\n"
                )
                pair_count += 1
            n_events += 1

    with open(OUT_STA, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["sta", "stla", "stlo"])
        for sta, la, lo in sorted(station_set):
            w.writerow([sta, f"{la:.4f}", f"{lo:.4f}"])

    print(f"tele events appended : {n_events}")
    print(f"cs pairs written     : {pair_count}")
    print(f"tele stations        : {len(station_set)}")
    print(f"wrote {OUT_FILE}")
    print(f"wrote {OUT_STA}")


if __name__ == "__main__":
    main()
